num_vec <- c(1.1, 2.2, 3.3)
char_vec <- c("A", "B", "C")
log_vec <- c(TRUE, FALSE, TRUE)

print(num_vec)
print(typeof(num_vec))
print(char_vec)
print(typeof(char_vec))
print(log_vec)
print(typeof(log_vec))